seccomp: use a static inline for a function stub
BugLink: http://bugs.launchpad.net/bugs/1509489

Fixes this error message when CONFIG_SECCOMP is not set:

arch/powerpc/kernel/ptrace.c: In function 'do_syscall_trace_enter':
arch/powerpc/kernel/ptrace.c:1713:2: error: statement with no effect [-Werror=unused-value]

Signed-off-by: Stephen Rothwell <sfr@ozlabs.au.ibm.com>
Signed-off-by: James Morris <james.l.morris@oracle.com>
(backported from commit b1fa650c7e6e81ca788fef52b1659295eb82ffdd)
Signed-off-by: Kyle Fazzari <kyle@canonical.com>
Acked-by: Kamal Mostafa <kamal@canonical.com>
Signed-off-by: Tim Gardner <tim.gardner@canonical.com>